### ISSUE TITLE
Mashup Container Profile not run

### ISSUE THREAD

**Issue by xesco123** [RuiRomano/pbigtwmonitor#10]
Good morning.
I can't get "Mashup Container Profile" to work since I updated the Gateway.

**Comment by dennisate** [comment]
I'm encountering the same error.  

It appears to be failing at this step:
= Table.AddColumn(#"Expanded Custom", "Custom", each Table.FromRecords( Json.Document(Text.Combine(List.Skip(Lines.FromBinary([Content]),7)))))

I'm attaching the MashupContainerProfiles.log file that is the source for this particular query.  Could this be due to a recent update of the log file format?
[MashupContainerProfiles.log](https://github.com/RuiRomano/pbigtwmonitor/files/11796171/MashupContainerProfiles.log)

**Comment by RuiRomano** [comment]
Exactly, the MashupContainerProfiles.log on the latest update is not longer a valid JSON file (after line 6) and I cannot simply read it with Json.Document.
I'm waiting for a confirmation from the Gateway team if this change is permanent to fix the template

**Comment by RuiRomano** [comment]
Fixed this issue today, by adapting the PowerQuery to the new file format.

**Comment by aruncser** [comment]
@RuiRomano Looks like its again happening with mashup container profile after Nov23 gateway upgrade.
